server:
  port: 8080
  servlet:
    context-path: /api
spring:
  data:
    redis:
      host: vm.local
      port: 6379
      password: '!@#123'
      database: 1
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://vm.local:3306/auth_system?serverTimezone=UTC
# mybatis ??
mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true